### ISSUE TITLE
API Error: could not fetch token

### ISSUE THREAD

**Issue by martijnmichel** [vfosterm/NordVPN-NetworkManager-Gui#15]
I get this error when trying to login on manjaro.

**Comment by vfosterm** [comment]
Seems like Nord has changed something in their undocumented api. I will try
to fix this tomorrow.

**Comment by vfosterm** [comment]
I've released a work around for this in the most recent version (v1.4.1)
I will attempt to find a better solution for this, apparently there is a new API in the works.
I will close this for now but let me know if you have any further issues.

**Comment by martijnmichel** [comment]
Still doesnt work here.. although im not sure if i need to remove the package first.
Is it possible to install this with pamac or trizen ?
